name: yarian
favicon: null
layout_spectrum: 0.60747
typography_spectrum: 0.67435
title: Mark Yarian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e7966'
    - '#f4daa1'
    - '#704d39'
    - '#000008'
    - '#59191f'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
