name: yarian
favicon: null
layout_spectrum: 0.27437
typography_spectrum: 0.43724
title: Mark Yarian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeced'
    - '#bcaead'
    - '#7d7c7a'
    - '#84642f'
    - '#6b3535'
  brandStrength: 0.3125
  lightness: 0.9628662371542305
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
