name: yarian
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60451
title: Mark Yarian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e7966'
    - '#f4daa1'
    - '#704d39'
    - '#000008'
    - '#59191f'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
