name: yarian
favicon: null
layout_spectrum: 0.47053466481156647
typography_spectrum: 0.8355510053224862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#554428'
    - '#837457'
    - '#b4996c'
  brandStrength: 0.967698491178453
  lightness: 0.9628662371542305
  saturation: 0.612551387399435
  rhythmicContrast: 0.37321224506013095
purpose: []
